
server:
  port: 8091

spring:
  application:
    name: ms-files
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/sis-323}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
    jpa:
      hibernate:
        ddl-auto: none
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

keycloak:
  auth-server-url: http://localhost:8080
  autodetect-bearer-only: true
  credentials:
    secret: CalOb9h83bEQEGYqaduEg0p4CFzaNnEa
    realm: sis-323
    resource: pm-backend

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka/}


minio:
    url: ${MINIO_URL:http://localhost:9000}
    access-key: ${MINIO_ROOT_USER:XdkMXb6fY6Rg8rXAhGXw}
    secret-key: ${MINIO_ROOT_PASSWORD:K1WgO7CEZr3QBU9MUpr26l0xpUl0IafYnb0lKbNT}
    bucket-name: ${MINIO_BUCKET_NAME:pm-files}

